spring:
  application:
    name : eureka-client
server:
  port : 2001

eureka:
  client:
    serviceUrl:
      defaultZone : http://admin:admin@pert1:1001/eureka/,http://admin:admin@pert2:1002/eureka/
  instance:
    hostname : pert1
    instance-id : ${spring.cloud.client.ipAddress}:${server.port}

