## 应用注册在server的名字
spring:
  cloud:
    config:
      server:
        git:
         uri: https://github.com/persistInHacker/springcloudStudy.git
         username:
         password:
## 应用端口
server:
  port : 6001

#eureka:
#  client:
#    serviceUrl:
#      defaultZone : http://admin:admin@pert1:1001/eureka/,http://admin:admin@pert2:1002/eureka/  
#  instance:
#    hostname : pert1
#    instance-id : ${spring.cloud.client.ipAddress}:${server.port}

